### ISSUE TITLE
store UI

### ISSUE THREAD

**Issue by matjazonline** [carlbarrdahl/reef-payment-api#1]
Hi, I'm having some issues with UI on your test deployment https://reef-payment-api.web.app/shop - can't see form elements and can't enter into input fields.
Please check, thank you!

<img width="675" alt="Screenshot 2021-11-10 at 17 46 58" src="https://user-images.githubusercontent.com/1091110/141156697-366f0e4e-9106-4c72-b0c3-0aa85084e666.png">

**Comment by carlbarrdahl** [comment]
> Hi, I'm having some issues with UI on your test deployment https://reef-payment-api.web.app/shop - can't see form elements and can't enter into input fields. Please check, thank you!
> 

What browser are you using? Seems to be working fine for me in Brave, Chrome and Firefox.
Also, can you see if there are any errors in the console? 

Edit: Maybe try in an incognito window also to see if there could be an extension causing it?
